server:
  port: 5555

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ge?autoReconnect=true
    username: root
# PC
#    password: 1234
# Labotary
    password: 123456
    driverClassName: com.mysql.jdbc.Driver