server:
  port: 5555

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/vocabulary?autoReconnect=true
#    username: root
##    password: root2mysql
##    password: 123456
#    password: 1234
#    driverClassName: com.mysql.jdbc.Driver